[package]
name = "rbcachefs"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = [ "staticlib" ] 

[build-dependencies]
cbindgen = "0.20.0"
pkg-config = "0.3"
