#ifndef RBCACHEFS_H
#define RBCACHEFS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


#define RBCH_SUPERBLOCK_MAGIC 263880070639002465776974858631536864641ULL

int32_t RS_mount_main(void);

#endif /* RBCACHEFS_H */
