name: cross build many arch with buildx, check, .debs into artefacts

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: bcachefs-tools-builder

jobs:

  buildx-matrix:
    runs-on: ubuntu-latest
    env:
        IMAGE_ID: ${{ needs.prepare_all_buildx.outputs.IMAGE_ID }}
        VERSION: ${{ needs.prepare_all_buildx.outputs.VERSION }}
        SHORTIMAGENAME:
    strategy:
        matrix:
          platform: [ amd64, arm64 ]
          include:
            - platform: arm64
              buildxplatform: linux/arm64
              strategy.fail-fast: false
            - platform: amd64
              buildxplatform: linux/amd64
              strategy.fail-fast: true
#            - platform: armv7
#              buildxplatform: linux/arm/v7
#              strategy.fail-fast: false
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Docker Setup Buildx
      id:   buildx
      uses: docker/setup-buildx-action@v2
    -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: git checkout
      uses: actions/checkout@v3

    -
        name: Prepare container names
        id: setvars
        run: |
          #IMAGE_ID=$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID="ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME"
          SHORTIMAGENAME="${IMAGE_ID}:${{ matrix.platform }}"
          echo IMAGE_ID=$IMAGE_ID
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo SHORTIMAGENAME: ${SHORTIMAGENAME}
          echo "SHORTIMAGENAME=$SHORTIMAGENAME" >> $GITHUB_ENV
          echo VERSION=$VERSION

          echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_OUTPUT
          echo "SHORTIMAGENAME=${SHORTIMAGENAME}"  >> $GITHUB_OUTPUT
          #echo "::set-output name=VERSION::$VERSION"
    - name: run build in container ${{ matrix.platform }}
      run: |
          #SHORTIMAGENAME="${IMAGE_ID}:${{ matrix.platform }}"
          echo SHORTIMAGENAME ${SHORTIMAGENAME}
          docker run --platform ${{ matrix.buildxplatform }} \
            -v ${{ runner.workspace }}:/build ${SHORTIMAGENAME} \
            sh -c "pwd; cd /build/bcachefs-tools; make; make mount.bcachefs; make deb "

    - name: show vars
      run: |
          pwd
          ls -l
          ls -l ../
          echo $(env)
          echo github.workspace ${{ github.workspace }}


    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: bcachefs-tools_debs_${{ matrix.platform }}-${{ github.sha }}
        retention-days: 10
        path: |
              ${{ runner.workspace }}/bcachefs-tools_*
              ${{ runner.workspace }}/bcachefs-tools-dbgsym*

