name: x64 build, check

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build deps install
      uses: lyricwulf/abc@v1.2.0
      with:
        linux:
          pkg-config libaio-dev libblkid-dev libkeyutils-dev
          liblz4-dev libscrypt-dev libsodium-dev liburcu-dev libzstd-dev
          uuid-dev zlib1g-dev valgrind libudev-dev python3 python3-docutils
          python3-pytest libfuse3-dev 
          devscripts debhelper
    - uses: actions/checkout@v3.5.3
    - name: make
      run: make
    - name: make deb
      run: make deb
    - name: show vars
      run: |
          pwd
          ls -l
          ls -l ../
          echo $(env)
          echo github.workspace ${{ github.workspace }}


    # - name: smoketests deps install
      # uses: lyricwulf/abc@v1.2.0
      # with:
        # linux:
          # libfuse3-dev python3-pytest-xdist valgrind
#    - name: smoke_test
#      run: ./smoke_test

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: debs x64 ${{ github.sha }}
        retention-days: 10
        path: |
              ${{ runner.workspace }}/bcachefs-tools_*
              ${{ runner.workspace }}/bcachefs-tools-dbgsym*
              
    - name: show vars
      run: |
          # echo pwd
          # pwd
          # ls -l
          # ls -l ../
          # echo $(env)
          # echo github.workspace ${{ github.workspace }}
          # ls ${{ github.workspace }}/
          # echo runner.workspace ${{ runner.workspace }}
          # ls ${{ runner.workspace }}/
          mkdir debs
          cp ../*.deb debs/ 
             
    - name: Deploy to packagecloud.io
      uses: lpenz/ghaction-packagecloud@v0.4
      with:
        repository: bcachefs/ubuntu/jammy
      env:
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
          