name: cross build with buildx, check, .debs into artefacts

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
    docker_platform: linux/arm/v7
jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Docker Setup Buildx
      id:   buildx
      uses: docker/setup-buildx-action@v1.6.0
    -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - uses: actions/checkout@v2
    - name: build image
      run: |
          BUILDER=builder
          cat << 'ENDDOCKERFILE' > Dockerfile
          ARG IMG=debian:bullseye
          FROM $IMG as deb

          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt-get update; apt-get install -y pkg-config libaio-dev libblkid-dev libkeyutils-dev \
                  liblz4-dev libscrypt-dev libsodium-dev liburcu-dev libzstd-dev \
                  uuid-dev zlib1g-dev valgrind libudev-dev git build-essential \
                  python3 python3-docutils \
                  python3-pytest devscripts debhelper
          WORKDIR /build
          
          ENDDOCKERFILE
          
          docker buildx build --platform ${{ env.docker_platform }} -t builder --load .
          
    - name: run build in container
      run: |          
          docker run --platform linux/arm/v7 -v ${{ runner.workspace }}:/build builder sh -c "pwd; cd /build/bcachefs-tools; ls -l; make; make deb"
          
    - name: show vars
      run: |
          pwd
          ls -l
          ls -l ../
          echo $(env)
          echo github.workspace ${{ github.workspace }}


    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: debs x64 ${{ github.sha }}
        retention-days: 10
        path: |
              ${{ runner.workspace }}/bcachefs-tools_*
              ${{ runner.workspace }}/bcachefs-tools-dbgsym*

