name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ABC Install
      uses: lyricwulf/abc@v1
      with:
        linux: 
          pkg-config libaio-dev libblkid-dev libkeyutils-dev 
          liblz4-dev libscrypt-dev libsodium-dev liburcu-dev libzstd-dev 
          uuid-dev zlib1g-dev valgrind libudev-dev
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make deb
      run: make deb
